#!/bin/sh

DBG=0
DEF=0

# get os

if [ -r /etc/os-release ]; then
  . /etc/os-release
#  echo "OS: " $ID
  VER=`echo $VERSION | awk '{print $1 }' | awk -F\. '{ print $1 }'`
#  echo "Version: " $VER

    if [ -f installers/${ID}-${VER}.sh ]; then
	echo "copy & paste the following command to begin the install:"
	echo
	echo " sh installers/${ID}-${VER}.sh | tee installer.log 2>&1"
	echo
    else 
	echo "$ID version $VER detected, but specific installer not found"
	echo "You can try the installer that seems most closely related to this OS"
	echo "(scripts in the installers directory)"
    fi
else 
    echo "OS detection did not provide unambiguous results."
    echo "refer to the docs directory for manual install procedures"
fi
